### ISSUE TITLE
MECH2100

### ISSUE THREAD

**Issue by tranjamin** [uqmars/MARS-Subject-Guide#15]
Prerequisite for MECH2100 is MECH2305 (not a mechatronics course).
Tyson currently checking issue

**Comment by lambdanon** [comment]
maybe we could email mech&mining.... is it an enforced prerequisite?

**Comment by lambdanon** [comment]
whoops accidentally closed it

**Comment by tranjamin** [comment]
None of the prereqs are really enforced
Tyson is aware of this and hopefully will fix it on the uq website, but just raising the issue here so we remember to change the tex

**Comment by lambdanon** [comment]
I've just made a commit that lists MECH2305 as a recommended prerequisite. Should be good enough

**Comment by tranjamin** [comment]
Ok sure
Can anyone who's done mech2100 support having mech2305 as recommended
