### ISSUE TITLE
Add Hyperlinks and Course Names to the Subject Lists

### ISSUE THREAD

**Issue by ThatSealgair** [uqmars/MARS-Subject-Guide#5]
It will be more accessible to students if we include the course name with the course code and have that set as a hyperlink for readers to get more information.

**Comment by q-horton** [comment]
My thinking was keep it to just course codes for the enrolment plan and similar for to minimise space, but have names and so forth laid out in the Course Profiles section. Hyperlinks is absolutely a great idea though, we can have all those lone course codes link to the profiles.

**Comment by ThatSealgair** [comment]
That suggestion sounds good to me. Let's do that!
